persistence: state.pickle
api_key: 123456789:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
admin_id: 987654321
bot_name: slateboy
locale: en
fallback: en
logfile: slateboy.log
min_cnt: 1000
min_ts: 86400
req_min_cnt: 1000
req_min_ts: 86400
max_request_age: 86400
max_withdrawal_age: 600
